### ISSUE TITLE
svg elements class attribute cannot use set_class(), but must use set_attribute()

### ISSUE THREAD

**Issue by bestia-dev** [fitzgen/dodrio#125]
I have a node like this  
```<svg class="myclass">...</svg>```
It returns an error, that the object className is read-only.  
I found that for svg element and its subelements we cannot call javascript className.  
We must call javascript setAttribute instead. 
It looks that this way works fine in general also for all other html elements.  
<https://stackoverflow.com/questions/33451050/classname-vs-get-setattribute-method>
I tried this change in change_list/mod.rs and it works for what I tested.  
And it also simplifies the code.  
```rust
    pub fn set_attribute(&mut self, name: &str, value: &str) {
        debug_assert!(self.traversal_is_committed());
        // Luciano: if it is a svg element than also class must use set_attributes
        /*
        if name == "class" {
            let class_id = self.ensure_string(value);
            debug!("emit: set_class({:?})", value);
            self.state.emitter.set_class(class_id.into());
        } else {
            */
            let name_id = self.ensure_string(name);
            let value_id = self.ensure_string(value);
            debug!("emit: set_attribute({:?}, {:?})", name, value);
            self.state
                .emitter
                .set_attribute(name_id.into(), value_id.into());
                /*
        }
        */
    }
```

**Comment by awestlake87** [comment]
I ran into this issue as well (although, I'm using the master branch of dodrio, so I don't expect things to always work as they should).

@LucianoBestia's fix worked for me though, thanks!

**Comment by awestlake87** [comment]
@LucianoBestia you may also be interested to know that the `ElementBuilder::namespace` function is pretty important for SVG elements. My elements were not displaying properly, at least in firefox, until I added `namespace(Some("http://www.w3.org/2000/svg"))` to them.

~In fact, it's still not 100% working as of now, and I suspect that might be because there is a `setAttributeNs` function in Javascript as well that might not play well with certain, or any, SVG attributes. I'm gonna try and get this working on my own real quick.~

Initially, I thought the namespace was supposed to be "svg", not "http://www.w3.org/2000/svg". After I changed it, the elements started behaving as anticipated.

BTW, sorry if this is out of the scope of the issue, I just thought I'd share that since it was not immediately obvious why things weren't working for me.

**Comment by bestia-dev** [comment]
Thanks.
Same here. I had a lot of problems make it work because SVG uses namespaces.  
I hate this namespace mess in xml, but we must live with it.  
I am working on a simple html templating for dodrio.  I use it inside a small game.  
<https://github.com/LucianoBestia/mem6_game/blob/master/mem6/src/htmltemplatemod.rs>
And I use  
```rust
if let HtmlOrSvg::Svg = html_or_svg_local {
   child_element = child_element.namespace(Some("http://www.w3.org/2000/svg"));
}
```

**Comment by awestlake87** [comment]
Cool! I'm just getting started with dodrio, so I might check it out if I run into any hiccups.
