### ISSUE TITLE
async alternative to with_components

### ISSUE THREAD

**Issue by bestia-dev** [fitzgen/dodrio#139]
I don't have enough experience, so I have to ask. 
Async/await and callbacks are a hard nut to crack.
it is about `vdom.with_component...(...) ...`
It executes a function passed as parameter with a reference to this virtual DOM's root rendering component.
Is it possible to use async/await to avoid passing a function? 
So the code will be written just like a "normal sync" code flow.
Is it possible something like this :

``` rust
//here we have vdom and y
spawn_local(async move {
    let root = vdom.get_root().await;
    let rrc = root.unwrap_mut::<RootRenderingComponent>();
    rrc.x = y;
})
```
Thank you for your patience.

**Comment by fitzgen** [comment]
The problem is that the root component's borrow is only valid for one tick of the event loop. Returning a future or taknig an async closure would allow code to do invalid things like:

```rust
let root = vdom.get_root().await;
let rrc = root.unwrap_mut::<RootRenderingComponent>();
rrc.x = y;

something_on_next_tick_of_event_loop.await;

// not valid
rrc.foo()
```

**Comment by bestia-dev** [comment]
Thanks.

**Comment by extraymond** [comment]
@LucianoBestia 

I've try to get that worked by wrapping the root vdom into a stream, and let it reacts to mutation messages. 

Each messages is defined as a agent capable of mutating a guarded data, and will get a finish event if data is mutated. And if the data mutated needed to update the view, it will send a message to notify the vdom message queue to scan on the current node of trees and let dodrio update/remove attributes/nodes and other dom manipulations.

So that way, I can design a react-like component which can chain tasks and resolve them in a more predictable manner.

Reference:
1. vdom inside a message queue(https://github.com/extraymond/afterglow/blob/43aa8c6bc25d296628138f4cd4d70bb4a3f6e01e/afterglow/src/container.rs#L154)
2. use mutex to guard mutation(https://github.com/extraymond/afterglow/blob/43aa8c6bc25d296628138f4cd4d70bb4a3f6e01e/afterglow/src/container.rs#L86)
3. wrapped closure to consume a web_sys::Event and sent a custom message(https://github.com/extraymond/afterglow/blob/43aa8c6bc25d296628138f4cd4d70bb4a3f6e01e/afterglow/src/messenger.rs#L42)
