### ISSUE TITLE
Roadmap to being not experimental

### ISSUE THREAD

**Issue by ijsnow** [fitzgen/dodrio#176]
Hey, this looks like a really cool project. Are there plans for moving it out of the experimental space? I'd love to use this in the future or at least something like [iced-web.](https://github.com/hecrj/iced/tree/master/web) I've got spare time and could help with work but I don't see a roadmap anywhere in the repo. Thanks!

**Comment by fitzgen** [comment]
There isn't a roadmap, no.

Dodrio was about getting ideas out there and showing people what's possible in terms of vdom implementation. I don't think this code base in particular needs to live on. If others think it should, they are encouraged to fork it and continue the experiment externally.

**Comment by yoshuawuyts** [comment]
We recently announced [localghost](https://github.com/mild-times/localghost): ergonomic bindings to the Web platform. And with it have spun up the [mild-times](https://github.com/mild-times) org to host work on the Web platform for Rust. The plan is to keep working on primitives much like we've done for [http-rs](https://github.com/http-rs), and eventually building a framework, `mild`, using these primitives.

Some early work on `mild` has begun, and we're been using `dodrio` for the rendering layer. However since `mild`'s rendering layer is required to be async, we've been patching `dodrio` to support that. We're not quite done with that yet, but once we do we'll want to either upstream the patches or publish a fork.

As far as the `mild` org is concerned, we'd be happy to continue work on `dodrio` there. Whether it is by moving the project, or maintaining an async-enabled fork. We're keen to progress the project and work with others who share our goals of enabling more people to start using Rust on the Web.

In related news: we recently were granted ownership of the `html` crate name on crates.io. And the plan is to take a path similar to `web-sys` to generate type-safe interfaces for HTML using their WebIDL definitions for an `html-sys` crate. Which we then wrap in user-friendly constructors through the `html` crate. We're still in the early phases of the project, but one of the goals is to be able to leverage this for construction of nodes in virtual DOMs.

**Comment by ijsnow** [comment]
@yoshuawuyts that's exciting! I'm definitely keen on using rust in the web. I've got the spare time so I'd be open to contributing as well.
