### ISSUE TITLE
Restrictive lifetimes for attr function

### ISSUE THREAD

**Issue by rylev** [fitzgen/dodrio#39]
The attr function currently has the following signature. 

```rust
fn attr<'a>(name: &'a str, value: &'a str) -> Attribute<'a> 
```

Inside a render function, I'd like to create a `String` for the value of the attribute (using `format!`). It would be nice if I had the choice to pass ownership of this string to the Attribute.

**Comment by fitzgen** [comment]
Yes, this is an unfortunate downside of the bump allocation strategy: you need to use `bumpalo::format!` and `into_bump_str` instead of regular `format!` and passing ownership. This approach allocates the formatted string in bump arena. Eventually, the `std` collection types will be parameterised by a custom allocator type, and we should be able to improve ergnomics a bit, but we don't have a ton of options until then.

Example: https://github.com/fitzgen/dodrio/blob/master/examples/counter/src/lib.rs#L38 and https://github.com/fitzgen/dodrio/blob/master/examples/counter/src/lib.rs#L57

**Comment by rylev** [comment]
Makes sense. Closing for now
