### ISSUE TITLE
I need help how to access app_data from Rendering Components in Dodrio.

### ISSUE THREAD

**Issue by bestia-dev** [fitzgen/dodrio#78]
I prepared a simple working example here:
https://github.com/LucianoBestia/dodrio_multi_component

My question is if there is a way to have `static borrow checker` in that example in compile time..
Now I use Rc and RefCell and that is `dynamic borrow chcker` in runtime.

Thanks.

**Comment by fitzgen** [comment]
One approach would be to do the following:

* Make `AppData` *be* the root rendering component,

* Make each of the header/footer/etc components look like this:

  ```rust
  struct HeaderRenderingComponent<'a> {
      app_data: &'a AppData,
  }

  impl<'a> Render for HeaderRenderingComponent<'a> {
      fn render<'b>(&self, ctx: &mut RenderContext<'b>) -> Node<'b> {
          // use self.app_data here...
      }
  }
  ```

* Any event handlers would cast the root rendering trait object to an `AppData` and work with it there:

  ```rust
  .on("click", move |root, vdom, _event| {
      let app_data = root.unwrap_mut::<AppData>();
      app_data.update_from_header();
      vdom.schedule_render();
  })
  ```

**Comment by bestia-dev** [comment]
Thank you. Your suggestion is the first approach I tried.
My goal is to create reusable and cacheable components, that can easily be used in different RootRenderingComponents.
I would like to have an update method on `HeaderRenderingComponent`.  So I can reuse this component with other `RootRenderingComponents`. 
If the RootRenderingComponent (app_data) does not include/reference HeaderRenderingComponent, I cannot call a method on it from `app_data.update_from_header()`.
And also I cannot cache the HeaderRenderingComponent, that will change rarely.
If I put a reference than I got a self-referencing struct.  
Maybe I could use Pin<> here to allow self_referencing struct?

For experimentation I took another approach now: I save cached data inside the components. Only the data that is needed for rendering the Component. This data is copied/cloned from app_data. I don't like copying/cloning, but this enables an easy invalidation od dodrio::cache with a single function. In this example the data is small and copying/cloning is not a problem. For bigger data it should be another solution.
  
I changed the code:
https://github.com/LucianoBestia/dodrio_multi_component

**Comment by bestia-dev** [comment]
I discovered, that the only problem I have with the classic approach you recommend is the use of dodrio::cache. All this acrobatics is because of that.
It requires the Render method in subComponents, but there I cannot send app_data as a parameter. If that was possible, there will be no problem at all. 
I created a working example of the "classic approach" in the folder `dodrio_components_classic\` in
https://github.com/LucianoBestia/dodrio_multi_component
I would like to hear some more about dodrio::cache for this use-case.

**Comment by bestia-dev** [comment]
I found RenderContext now and maybe this is the path to my solution. I will explore.
Probably I need to use dodrio::CacheSet here. I added the source code to my project, to have the new features, that are not in crates.io.

**Comment by fitzgen** [comment]
Yeah there have been a few breaking changes in master that will be in the 0.2.0 release, including the `RenderContext` stuff and changes to the `Render` trait.

You shouldn't need to use `CachedSet` yourself -- that's an internal type.

I would avoid using `Cached` until you see the need for it, and then do the necessary refactoring. You are right that using `Cached` means you generally need a component that doesn't have borrows, which means that if it needs to share data with other things, it needs to use `Rc`s or something. This is a pretty fundamental property, in that there isn't really any design alternative. In this scenario, you probably want one central state wrapper type that hides the `Rc<RefCell<..>>` internally, and you dispatch messages to, sort of like elm/redux, and the message dispatch method would do the dynamic borrow before calling all the appropriate message handlers. This way you only have a single `Rc` and `RefCell` instead of a soup of them all over the place, and it is also hidden and the user-facing API is pleasant to use.

For reusable components, I suggest making them generic over some sort of actions/controller trait that users can implement to make the component do whatever they want, sort of like the TodoMVC example: https://github.com/fitzgen/dodrio/blob/master/examples/todomvc/src/todo.rs#L9-L173

**Comment by bestia-dev** [comment]
Thanks. I think I don't understand caching well enough. 
I will wait until some good example of how to use it properly.
In the meantime, I will play around with some different approaches, just for learning.

**Comment by bestia-dev** [comment]
Thank you very much for adding Cached<> to 
examples/todomvc/src/todo.rs
It helps me a lot to have a working example.
